# Generated by Django 4.2.3 on 2023-08-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='oneradio',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='perimg',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='secradio',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='thirdradio',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=100),
        ),
    ]
