# Generated by Django 4.2.3 on 2023-08-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainform', '0002_alter_studentdata_oneradio_alter_studentdata_perimg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itser', models.CharField(max_length=300)),
                ('langser', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='dob',
            field=models.CharField(max_length=100, verbose_name='birth'),
        ),
    ]
