# Generated by Django 4.2.3 on 2023-08-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainform', '0005_langservices_rename_services_itservices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='frontendchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='media/logo')),
                ('mainname', models.CharField(max_length=100)),
                ('firsttitle', models.CharField(max_length=150, verbose_name='First Page Title')),
                ('sectitle', models.CharField(max_length=150, verbose_name='Second Page Title')),
                ('thirdtitle', models.CharField(max_length=150, verbose_name='Third Page Title')),
                ('forthtitle', models.CharField(max_length=150, verbose_name='Forth Page Title')),
                ('fifthtitle', models.CharField(max_length=150, verbose_name='Fifth Page Title')),
                ('queone', models.CharField(max_length=300, verbose_name='Question one')),
                ('quesec', models.CharField(max_length=300, verbose_name='Question second')),
                ('quethird', models.CharField(max_length=300, verbose_name='Question third')),
                ('firstsertitle', models.CharField(max_length=100, verbose_name='Fisrt Service Title')),
                ('secsertitle', models.CharField(max_length=100, verbose_name='Second Service Title')),
                ('queforth', models.CharField(max_length=300, verbose_name='Question forth')),
            ],
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='perimg',
            field=models.ImageField(upload_to='media/profile_pic'),
        ),
    ]
