# Generated by Django 4.2.3 on 2023-08-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainform', '0006_frontendchanges_alter_studentdata_perimg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frontendchanges',
            options={'verbose_name': 'frontendchanges', 'verbose_name_plural': 'Front-end Changes'},
        ),
        migrations.AlterField(
            model_name='frontendchanges',
            name='queforth',
            field=models.TextField(verbose_name='Question Forth'),
        ),
        migrations.AlterField(
            model_name='frontendchanges',
            name='queone',
            field=models.TextField(verbose_name='Question one'),
        ),
        migrations.AlterField(
            model_name='frontendchanges',
            name='quesec',
            field=models.TextField(verbose_name='Question second'),
        ),
        migrations.AlterField(
            model_name='frontendchanges',
            name='quethird',
            field=models.TextField(verbose_name='Question third'),
        ),
    ]
