# Generated by Django 4.2.3 on 2023-08-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainform', '0007_alter_frontendchanges_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendchanges',
            name='backgroundimg',
            field=models.ImageField(default=0, upload_to='media/backimg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frontendchanges',
            name='fevi',
            field=models.ImageField(default=0, upload_to='media/fevi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frontendchanges',
            name='title',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
